import {
  InitForm,
  ChangeField,
  SetField,
  //SetFormValid,
  TouchField,
  FocusField,
  ResetForm,
  SetFormUndirty,
  ResetFormAfterNavigation,
  ValidateForm,
  ValidateDataType,
  ValidateSchema,
  ValidateList,
  FillListControl,
} from "./library/forms/actions"

import {
  NavigateBack,
  NavigateTo,
  Logout,
  InitApp,
  RehydrateApp,
  GetFile,
  AfterRehydrateApp,
  SetLanguage,
  SetVisibleFalse,
  SetTableNeedsRebuild,
  SetLastScrollPosition,
} from "./global/actions"

import {
  AddSnack,
  RemoveSnack,
  PlaceSnack,
  ClearSnack,
} from "./library/Snack/actions"

import {
  ModalDialogOpen,
  OkDialog,
  OkCancelDialog,
  DialogOpen,
  DialogClose,
} from "./library/Dialog/actions"
let dialog = {
  DialogOpen,
  DialogClose,
  ModalDialogOpen,
  OkDialog,
  OkCancelDialog,
}

let form = {
  InitForm,
  ResetForm,
  ResetFormAfterNavigation,
  ValidateForm,
  SetField,
}

import {
  DialogChanged,
  //DialogClosed,
  DialogDefaultChanged,
  SetIndicatorClose,
  SetIndicatorOpen,
  TableRefresh,
  TableInit,
  TableRebuild,
  TableSelectRow,
  TableClearFilter,
  TableSelectHeader,
  TableSort,
  TableFilter,
  TableFilterSelected,
  TableSetPage,
  TableDeleteRow,
  TableCopyRow,
  TableEditRow,
  TableSelectAll,
  TableEditSaveRow,
  TableDirectSaveRow,
  TableEditClose,
  TableMoreRow,
  TableViewRow,
  TableCloseViewRow,
  TableAddRow,
  TableDeleteRowFromData,
  TableMultipleDeleteRow,
  TableMultipleCopyRow,
  TableMultipleEditRow,
  TableMultipleCustomFunction,
  TableViewRefresh,
  TableRefreshDataFromServer,
  TableSelectCustomSort,
  TableSelectCustomFilter,
  TableSelectColumnFilter,
  TableSetViewTab,
  TableOfflineRetryDeleteRow,
  TableOfflineRetrySaveRow,
  TableOfflineHandler,
} from "./library/actions"

let navigation = { NavigateBack, NavigateTo }

let indicator = { SetIndicatorOpen, SetIndicatorClose }

let table = {
  TableRefresh,
  TableInit,
  TableRebuild,
  TableSelectRow,
  TableEditRow,
  TableDeleteRow,
  TableEditClose,
  TableViewRefresh,
  TableRefreshDataFromServer,
  TableSort,
  TableFilter,
  TableClearFilter,
  TableAddRow,
  TableDirectSaveRow,
  TableSetViewTab,
}

let internal = {
  SetTableNeedsRebuild,
  SetLastScrollPosition,
  PlaceSnack,
  ClearSnack,
  AddSnack,
  RemoveSnack,
  DialogChanged,
  //DialogClosed,
  DialogDefaultChanged,
  TableSelectHeader,
  TableFilterSelected,
  TableSetPage,
  TableCopyRow,
  TableDeleteRow,
  TableAddRow,
  TableEditRow,
  TableSelectAll,
  TableEditSaveRow,
  TableDirectSaveRow,
  TableMoreRow,
  TableViewRow,
  TableCloseViewRow,
  TableDeleteRowFromData,

  TableMultipleDeleteRow,
  TableMultipleCopyRow,
  TableMultipleEditRow,
  TableMultipleCustomFunction,
  TableSelectCustomSort,
  TableSelectCustomFilter,
  TableSelectColumnFilter,
  TableOfflineRetryDeleteRow,
  TableOfflineRetrySaveRow,
  TableOfflineHandler,
  InitApp,
  RehydrateApp,
  GetFile,
  AfterRehydrateApp,
  SetLanguage,
  SetVisibleFalse,
  ChangeField,
  SetField,
  TouchField,
  FocusField,
  //SetFormValid,
  ValidateDataType,
  SetFormUndirty,
  ValidateSchema,
  ValidateList,
  FillListControl,
}

let user = { Logout }

export { indicator, navigation, internal, dialog, form, table, user }
