import * as user from "./screens/Login/formActions"
import * as mobiletimerecording from "./screens/MobileTimeRecording/MobileTimeRecordingDetail/formActions"
import * as mobiletimerecordingmain from "./screens/MobileTimeRecording/formActions"
import * as settings from "./screens/Settings/formActions"
import * as translations from "./screens/Translation/formActions"
import * as feedback from "./screens/Feedback/formActions"
import {
  EditGetCaptionRender,
  Edit_U_Memo_GetLabelAndValueRender,
  FormCustom_memoContainsTest_Filter,
  FormCustom_memoContainsText_Filter,
  FormCustom_memoThenAlpha_Sort,
  ViewRowCellClass,
  Field_MobileSummary_GetLabelRender,
  Field_MobileSummary_GetValueRender,
  Field_U_Alpha_GetValueRender,
  Field_U_Decimal_RowCellSelectedHandler,
  Field_U_ItemCode_GetFilteredList,
  Field_U_ItemCode_GetLabelRender,
  Field_U_ItemCode_GetList,
  Field_U_ItemCode_GetValueRender,
  Field_U_ItemCode_HeaderCellSelectedHandler,
  Field_U_ItemCode_LookupPostData,
  Field_U_ItmsGrpCod_GetList,
  Field_U_ParentCode2_GetList,
  Field_U_ParentCode_GetList,
  FormAdd,
  FormAfterRender,
  FormCanDelete,
  FormCanEdit,
  FormChanged,
  FormCopy,
  FormCustomColumnFn_ValidValues,
  FormCustomFnSelect,
  FormCustom_alphaStartsWithA_Filter,
  FormCustom_alphaStartsWithB_Filter,
  FormCustom_alphaThenMemo_Sort,
  FormCustom_onlyTest_Sort,
  FormShow,
  FormStatus,
  FormValidate,
  ViewAfterRender,
  ViewCustomTab_TabX_Render,
  ViewCustom_tab1_Render,
  ViewGetCaptionRender,
  ViewHeaderCellClass,
  ViewShow,
} from "./shared/TableTesting/customActions"
import * as screens from "./customScreenActions"
let testtables = {
  tabletesting: {
    EditGetCaptionRender,
    Edit_U_Memo_GetLabelAndValueRender,

    ViewRowCellClass,
    Field_MobileSummary_GetLabelRender,
    Field_MobileSummary_GetValueRender,
    Field_U_Alpha_GetValueRender,
    Field_U_Decimal_RowCellSelectedHandler,
    Field_U_ItemCode_GetFilteredList,
    Field_U_ItemCode_GetLabelRender,
    Field_U_ItemCode_GetList,
    Field_U_ItemCode_GetValueRender,
    Field_U_ItemCode_HeaderCellSelectedHandler,
    Field_U_ItemCode_LookupPostData,
    Field_U_ItmsGrpCod_GetList,
    Field_U_ParentCode2_GetList,
    Field_U_ParentCode_GetList,
    FormAdd,
    FormAfterRender,
    FormCanDelete,
    FormCanEdit,
    FormChanged,
    FormCopy,
    FormCustom_alphaStartsWithA_Filter,
    FormCustom_alphaStartsWithB_Filter,
    FormCustom_alphaThenMemo_Sort,
    FormCustom_memoContainsTest_Filter,
    FormCustom_memoContainsText_Filter,
    FormCustom_memoThenAlpha_Sort,
    FormCustom_onlyTest_Sort,
    FormCustomColumnFn_ValidValues,
    FormCustomFnSelect,
    FormShow,
    FormStatus,
    FormValidate,
    ViewAfterRender,
    ViewCustomTab_TabX_Render,
    ViewCustom_tab1_Render,
    ViewGetCaptionRender,
    ViewHeaderCellClass,
    ViewShow,
  },
  mobiletimerecording,
  mobiletimerecordingmain,
}
let system = { user, translations }

export { screens, testtables, settings, system, feedback }
